apiVersion: v1
kind: Service
metadata:
  name: reddit-service
spec:
  type: LoadBalancer
  selector:
    app: reddit-app
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 8000