apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  generateName: hello-world-gke-
spec:
  entrypoint: whalesay
  templates:
  - name: whalesay
    container:
      image: docker/whalesay:latest
      command: [cowsay]
      args: ["hello GKE!"]
      securityContext:
        runAsUser: 1000